version: "3.4"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  imenik_backend:
    container_name: imenik_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"